name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Remplacez '5.0.x' par la version de .NET que vous utilisez

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run SonarCloud Scanner
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"Raptoor44_ApiProjetCube" /o:"raptoor44" /d:sonar.login="***" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build and Rebuild solution
        run: dotnet build --configuration Release --no-incremental
