on:
  push:
    branches:
      - production

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v30
          release_name: Release v30
          draft: true
          prerelease: false
          body: |
            Une nouvelle version a été proposée en réponse à un push vers la branche Production.
            - Commits ajoutés depuis la dernière release : 
            # Vous pouvez ajouter les détails des commits ici.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Ajoutez les étapes de construction et de publication de votre image Docker ici
      # Exemple :
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v30
