name: Scan de sécurité Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Scan de sécurité
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Exécution du scan Trivy
        run: |
          docker run --rm -v "$(pwd):/src" aquasec/trivy mcr.microsoft.com/dotnet/aspnet:6.0

