name: Scan de sécurité Trivy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    name: Scan de sécurité
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Exécution du scan Trivy
        run: |
          # Récupérer le token d'authentification pour accéder au registre des packages
          TOKEN=$(echo "${{ secrets.GITHUB_TOKEN }}")

          # Extraire l'image du registre des packages
          docker login docker.pkg.github.com -u joachim-organisation -p "${TOKEN}"
          docker pull docker.pkg.github.com/joachim-organisation/apiprojetcube/apiprojetcube:latest

          # Exécuter le scan Trivy sur l'image extraite
          docker run --rm -v "$(pwd):/src" aquasec/trivy docker.pkg.github.com/joachim-organisation/apiprojetcube/apiprojetcube:latest


