name: "Analyse de la viabilité de la branche master lors de la pull request"
on:
  pull_request:
    branches: [ "Production" ]
    
  schedule:
    - cron: '20 17 * * 5'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/joachim-organisation/apiprojetcube:${{ github.sha }} ./ApiProjetCube/

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/joachim-organisation/apiprojetcube:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Count critical vulnerabilities
        id: count-vulnerabilities
        run: |
          echo "::set-output name=count::$(jq -r '.runs[0].results[] | select(.properties["tags"] == "security") | select(.properties["severity"] | contains("CRITICAL")) | .properties["severity"]' trivy-results.sarif | wc -l)"

      - name: Check vulnerability count
        if: ${{ steps.count-vulnerabilities.outputs.count > 3 }}
        run: |
          echo "More than 3 critical vulnerabilities found. Cancelling the pull request..."
          # Add commands here to cancel the pull request using GitHub API"
          
      - name: Start Docker container
        run: |
         docker run -d -p 8080:80 --name my_container "ghcr.io/joachim-organisation/apiprojetcube:master" sh -c "while sleep 10; do :; done"
          sleep 10

      - name: Check container status
        run: |
          docker ps -a
          docker logs my_container

      - name: "Tests d'intégration."
        run: |
          # Les différents tests :
          # Le premier test qui permet de vérifier si l'api fonctionne bien.
          curl http://localhost:8080/health
          # Le second test qui permet de vérifier une requête GET des messages (Beaucoup de données).
          output=$(curl -s http://localhost:8080/api/Test)
            count=$(echo "$output" | jq '. | length')

            if [[ $count -ge 2 ]]; then
              echo "Plus de 2 messages ont été trouvés"
            else
              echo "Moins de 2 messages ont été trouvé"
              exit 1
            fi

      - name: Capture logs
        run: |
          docker logs my_container > logs.txt

      - name: Stop Docker container
        run: docker stop my_container
        
