name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
          tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          sudo chmod +x /usr/local/bin/trivy


